<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY8x80jm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY8x80jm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY8x80jm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY8x80jm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY8x80jm\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y8x80jm',
    'container.build_id' => 'fce80d9f',
    'container.build_time' => 1636572087,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY8x80jm');
