<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Program extends \App\Entity\Program implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Program' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Program' . "\0" . 'programPlan', '' . "\0" . 'App\\Entity\\Program' . "\0" . 'ownerId', '' . "\0" . 'App\\Entity\\Program' . "\0" . 'trainersId', '' . "\0" . 'App\\Entity\\Program' . "\0" . 'startDateTime', '' . "\0" . 'App\\Entity\\Program' . "\0" . 'finishDateTime', '' . "\0" . 'App\\Entity\\Program' . "\0" . 'trainings', '' . "\0" . 'App\\Entity\\Program' . "\0" . 'goal'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Program' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Program' . "\0" . 'programPlan', '' . "\0" . 'App\\Entity\\Program' . "\0" . 'ownerId', '' . "\0" . 'App\\Entity\\Program' . "\0" . 'trainersId', '' . "\0" . 'App\\Entity\\Program' . "\0" . 'startDateTime', '' . "\0" . 'App\\Entity\\Program' . "\0" . 'finishDateTime', '' . "\0" . 'App\\Entity\\Program' . "\0" . 'trainings', '' . "\0" . 'App\\Entity\\Program' . "\0" . 'goal'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Program $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getProgramPlan(): ?\App\Entity\ProgramPlan
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgramPlan', []);

        return parent::getProgramPlan();
    }

    /**
     * {@inheritDoc}
     */
    public function setProgramPlan(?\App\Entity\ProgramPlan $programPlan): \App\Entity\Program
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProgramPlan', [$programPlan]);

        return parent::setProgramPlan($programPlan);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwnerId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwnerId', []);

        return parent::getOwnerId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwnerId(int $ownerId): \App\Entity\Program
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwnerId', [$ownerId]);

        return parent::setOwnerId($ownerId);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrainersId(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrainersId', []);

        return parent::getTrainersId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrainersId(?array $trainersId): \App\Entity\Program
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrainersId', [$trainersId]);

        return parent::setTrainersId($trainersId);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartDateTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartDateTime', []);

        return parent::getStartDateTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartDateTime($startDateTime): \App\Entity\Program
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartDateTime', [$startDateTime]);

        return parent::setStartDateTime($startDateTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinishDateTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinishDateTime', []);

        return parent::getFinishDateTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinishDateTime($finishDateTime): \App\Entity\Program
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinishDateTime', [$finishDateTime]);

        return parent::setFinishDateTime($finishDateTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrainings(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrainings', []);

        return parent::getTrainings();
    }

    /**
     * {@inheritDoc}
     */
    public function addTraining(\App\Entity\Training $training): \App\Entity\Program
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTraining', [$training]);

        return parent::addTraining($training);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTraining(\App\Entity\Training $training): \App\Entity\Program
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTraining', [$training]);

        return parent::removeTraining($training);
    }

    /**
     * {@inheritDoc}
     */
    public function getGoal(): ?\App\Entity\GoalUser
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoal', []);

        return parent::getGoal();
    }

    /**
     * {@inheritDoc}
     */
    public function setGoal(?\App\Entity\GoalUser $goal): \App\Entity\Program
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGoal', [$goal]);

        return parent::setGoal($goal);
    }

}
